<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LPCAIQ1099" failures="1" tests="2" name="Default test(failed)" time="0.388" errors="0" timestamp="2022-11-30T14:11:18 EET">
  <testcase classname="Tests.Retry" name="Test2" time="0.159"/>
  <testcase classname="Tests.Retry" name="Test3" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Tests.Retry.Test3(Retry.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="Tests.Retry" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Default test(failed) -->
